# Generated by Django 3.2.13 on 2022-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='shomare_hesab',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
