# Generated by Django 4.0.4 on 2022-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_postinstagrami'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinstagrami',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
