# Generated by Django 3.2.13 on 2022-06-16 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_postinstagrami_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostInstagramiProxyAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['caption'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.postinstagrami',),
        ),
        migrations.CreateModel(
            name='FollowerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Accept'), ('r', 'Reject'), ('p', 'Pending')], max_length=1)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.followertable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='followertable',
            name='follower',
            field=models.ManyToManyField(related_name='followers', through='app.FollowerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followertable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
