# Generated by Django 3.2.13 on 2022-06-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220621_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='brth_year',
            new_name='birth_year',
        ),
    ]
