version: "3.7"

services:
  django_web:
    build: .
    command: >
      ash -c "python manage.py migrate && gunicorn todoRest.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ashkan
      - POSTGRES_PASSWORD=mapsa
      - POSTGRES_DB=todo
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8082:80
    depends_on:
      - django_web



volumes:
  postgres_data:
  static:
  media: