# Generated by Django 4.0.4 on 2022-04-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moshakhast',
            field=models.JSONField(default={}),
        ),
    ]
