# Generated by Django 4.0.4 on 2022-04-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_moshakhast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moshakhast',
            field=models.JSONField(default=dict),
        ),
    ]
