# Generated by Django 4.0.3 on 2022-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
